Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Controllers/RacaController.cs
using Entra21.CSharp.ClinicaVeterinaria.Repositorio.BancoDados;
using Entra21.CSharp.ClinicaVeterinaria.Repositorio.Enums;
using Entra21.CSharp.ClinicaVeterinaria.Servico;
using Entra21.CSharp.ClinicaVeterinaria.Servico.ViewModels.Racas;
using Microsoft.AspNetCore.Mvc;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Controllers
{
    //Dois pontos herança (mais pra frente)
    public class RacaController : Controller
    {
        private readonly IRacaServico _racaServico;
        private readonly List<string> _especies;

        //Construtor: Objetivo construir o objeto de RacaController, com o minimo
        //necessários para o funcionamento correto
        public RacaController(IRacaServico racaServico)
        {
            _racaServico = racaServico;
            //racaServico.Cadastrar(nome, especie);
        }
        /// <summary>
        /// Endpoint que permite listar todas as raças
        /// </summary>
        /// <returns>Retorna a página html com as raças</returns>

        [HttpGet("/raca")]

        public IActionResult ObterTodos()
        {
            var racas = _racaServico.ObterTodos();


            return View("Index", racas);
        }

        [HttpGet("/raca/cadastrar")]
        public IActionResult Cadastrar()
        {
            var especies = ObterEspecies();

            ViewBag.Especies = especies;

            var racaCadastrarViewModel = new RacaCadastrarViewModel();

            return View(racaCadastrarViewModel);
        }

        [HttpPost("/raca/cadastrar")]
        public IActionResult Cadastrar(
            [FromForm] RacaCadastrarViewModel racaCadastrar)
        {
            //if(ModelState == false) = mesma coisa que colocar um exclamação no início
            if (!ModelState.IsValid)
            {
                ViewBag.Especies = ObterEspecies();

                return View(racaCadastrar);
            }
            _racaServico.Cadastrar(racaCadastrar);

            return RedirectToAction("index");
        }

        [HttpGet("/raca/apagar")]
        //https://localhost:porta/raca/apagar?id=4
        public IActionResult Apagar([FromQuery] int id)
        {
            _racaServico.Apagar(id);

            return RedirectToAction("index");
        }

        [HttpGet("/raca/editar")]
        public IActionResult Editar([FromQuery] int id)
        {
            var raca = _racaServico.ObterPorId(id);
            var especies = ObterEspecies();
            var racaEditarViewModel = new RacaEditarViewModel()
            {
                Id = raca.Id,
                Nome = raca.Nome,
                Especie = raca.Especie
            };

            ViewBag.Especies = especies;

            return View(racaEditarViewModel);
        }

        [HttpPost("/raca/editar")]
        public IActionResult Editar(
            [FromForm] RacaEditarViewModel racaEditarViewModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Especies = ObterEspecies();
                return View(racaEditarViewModel);
            }
            _racaServico.Editar(racaEditarViewModel);

            return RedirectToAction("Index");
        }

        private List<string> ObterEspecies()
        {
            return Enum.GetNames<Especie>()
                            .OrderBy(x => x)
                            .ToList();
        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Controllers/VeterinarioController.cs
using Entra21.CSharp.ClinicaVeterinaria.Servico;
using Entra21.CSharp.ClinicaVeterinaria.Servico.ViewModels.Veterinarios;
using Microsoft.AspNetCore.Mvc;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Controllers
{
        [Route("/veterinario")]
    public class VeterinarioController : Controller
    {
        private readonly IVeterinarioServico _veterinarioServico;

        public VeterinarioController(IVeterinarioServico veterinarioServico)
        {
            _veterinarioServico = veterinarioServico;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost("/cadastrar")]
        public IActionResult Cadastrar(
            VeterinarioCadastrarViewModel veterinarioCadastrarViewModel)
        {
            if (!ModelState.IsValid)
                return View(veterinarioCadastrarViewModel);

            //Criar o registro chamado serviço
            _veterinarioServico.Cadastrar(veterinarioCadastrarViewModel);

            //Redirecionar para o index
            //return RedirectionToAction("Index");
            return RedirectToAction(nameof(Index));
        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Entra21.CSharp.ClinicaVeterinaria.Aplicacao.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CV dois irmãos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Entra21.CSharp.ClinicaVeterinaria.Aplicacao.styles.css" asp-append-version="true" />
    <h1 class="display-4">Bem vindo!!</h1>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CV SOS Dois Irmãos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Raca" asp-action="Index">Raças</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Entra21.CSharp.ClinicaVeterinaria.Aplicacao - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Views/Raca/Cadastrar.cshtml
@model RacaCadastrarViewModel
@{
    var especies = ViewBag.Especies as List<string>;
    especies.Add(string.Empty);

    var selectDasEspecies = new SelectList(especies, string.Empty);
}

<h3>Cadastro de Raça</h3>

<form asp-action="Cadastrar" method="POST">
    <div>
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Especie" class="form-label"></label>
        <select asp-for="Especie" asp-items="selectDasEspecies" class="form-select"></select>
            <span asp-validation-for="Especie" class="text-danger"></span>
        </div>
        <div class="text-end"
            <a href="/raca" class="btn btn-outline-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Salvar</button>
        </div>
</form>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Views/Raca/Editar.cshtml
@model RacaEditarViewModel
@{
    var especies = ViewBag.Especies as List<string>;
    especies.Add(string.Empty);

    var selectDasEspecies = new SelectList(especies, string.Empty);
}

<h3>Cadastro de Raça</h3>

<form asp-action="editar" method="POST">
    <input type="hidden" asp-for="Id" />
    <div>
        <label asp-for="Nome" class="form-label"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Especie" class="form-label"></label>
        <select asp-for="Especie" asp-items="selectDasEspecies" class="form-select"></select>
            <span asp-validation-for="Especie" class="text-danger"></span>
        </div>
        <div class="text-end"
            <a href="/raca" class="btn btn-outline-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Salvar</button>
        </div>
</form>

Entra21.CSharp.ClinicaVeterinaria/Entra21.CSharp.ClinicaVeterinaria.Aplicacao/Views/Raca/Index.cshtml
@model List<Raca>

<h1>Lista de Raças</h1>

<div class="row mab-2">
    <div class="text-end">
        <a asp-action="cadastrar"
           class="btn btn-primary">Cadastrar</a>
    </div>
</div>

<table class="table table-striped table-bordered">
    <thead>
        <!--Cabeçalho da tabela-->
        <tr>
            <!--Linha da tabela-->
            <th>Código</th><!--´Coluna especifica do cabeçalho-->
            <th>Nome</th>
            <th>Espécie</th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        <!--Lugar dos registros da tabela-->
        @foreach (var raca in Model)
        {
            <tr>
                <!--Linha-->
                <td>@raca.Id</td><!--Coluna específica para body-->
                <td>@raca.Nome</td>
                <td>@raca.Especie</td>
                <td>
                    <a asp-action="editar" asp-route-id="@raca.Id">Editar</a>
                    <a asp-action="apagar" asp-route-id="@raca.Id">Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>